using System;
using LanguageExt.Traits;

namespace LanguageExt;

/// <summary>
/// Represents a value to use in tail-recursive loops.  Usually understood to be the value t
/// pass to the next stage of the loop so it can continue (and either generated by the previous
/// loop-stage or is the initial trigger-value.
/// </summary>
/// <see cref="LanguageExt.Next"/>
/// <remarks>
/// On its own this doesn't do much, but  allows other types to convert from it and provide
/// binding extensions that mean it can be lifted into other monads without specifying lots
/// of extra generic arguments.
/// </remarks>
/// <param name="Value">Bound value</param>
/// <typeparam name="A">Bound value type</typeparam>
public readonly record struct Loop<A>(A Value)
{
    /// <summary>
    /// Functor map
    /// </summary>
    /// <param name="f">Mapping function</param>
    /// <typeparam name="B">Result bound value type</typeparam>
    /// <returns>Result of the applying the mapping function to the `Pure` value</returns>
    public Loop<B> Map<B>(Func<A, B> f) =>
        new (f(Value));

    /// <summary>
    /// Convert to a `Next` value
    /// </summary>
    public Next<A, B> ToNext<B>() =>
        Next.Loop<A, B>(Value);
}
